apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tribes.usermgmt.infra
spec:
  group: usermgmt.infra
  scope: Namespaced
  names:
    kind: Tribe
    singular: tribe
    plural: tribes
    shortNames:
    - tribes
    categories:
    - all
  versions:
  - name: v1alpha1
    served: true
    storage: true
    additionalPrinterColumns:
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              squads:
                type: array
                items:
                  type: string
              ttl: 
                type: array
                items:
                  type: string
              tl:
                type: array
                items:
                  type: string
              agilecoach:
                type: array
                items:
                  type: string
                default: []
              applications:
                type: array
                items:
                  type: string
                default: []
            required:
              - squads
              - ttl
              - tl
            type: object