apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: squads.usermgmt.infra
spec:
  group: usermgmt.infra
  scope: Namespaced
  names:
    kind: Squad
    singular: squad
    plural: squads
    shortNames:
    - squads
    categories:
    - all
  versions:
  - name: v1alpha1
    served: true
    storage: true
    additionalPrinterColumns:
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              applications:
                type: array
                items:
                  type: string
                default: []
              managers: 
                type: array
                items:
                  type: string
                default: []
              federatedDevops: 
                type: array
                items:
                  type: string
                default: []
              devops: 
                type: array
                items:
                  type: string
                default: []
              developers: 
                type: array
                items:
                  type: string
                default: []
              incidentManagers: 
                type: array
                items:
                  type: string
                default: []
              onCall: 
                type: array
                items:
                  type: string
                default: []
            required:
              - applications
              - managers
            type: object